services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shortlink-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8098:8098"

networks:
  default:
    name: dokploy-network
    external: true

