services:
  app:
    build: .
    container_name: shortlink_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8.0
    container_name: shortlink_mysql
    restart: always
    environment:
      MYSQL_DATABASE: shortlink
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"