services:
  app:
    build: .
    container_name: shortlink_app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8096:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

